### ISSUE TITLE
Very large datasets can cause prep process to hang

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-doi#78]
A very large dataset can cause parts of the preparation process to hang indefinitely.  The most recent occurrence involved three very large datasets (hundreds of GiB each, the largest being over 800 GiB) being prepared at the same time.  All three workers stopped during the `git annex uninit` phase.  It seems the `git-annex` process hanged for all three.  Killing the processes let the worker queue continue, but all subsequent zip files (for requests that were already in the queue) did not contain any annexed data.

**Comment by mpsonntag** [comment]
Currently when processing a DOI request, we are `gin` cloining a repository into an existing `git` directory on the DOI server.

In the above described example three DOI queue workers were trying to `annex uninit` three large datasets (~800GB, ~300GB and ~250GB) at the same time. Killing these processes left an annex directory in the parent `git` directory and left it in a `smudged` state.  since it seems, that annex is also added to the parent git directory.

It might be a good idea to clone DOI request repositories in a dedicated preparation directory that is not under git control and copy the resulting `zip` file into the hosting directory instead of creating it directly there.

**Comment by mpsonntag** [comment]
It seems, that the problem were git submodules in the offending repositories that caused the `annex uninit` to hang.

As described above, cloning the directories in a dedicated folder and creating the required `zip` file simply excluding the `.git` folder without running an `uninit` would circumvent the `submodules` problem and potentially speed up the registration process, since the repository does not need to be cloned a second time before uploading the annex content to the manual gin "DOI" user fork of the repository.

For these changes to take effect
-[ ] add a `staging` directory to the doi config file and struct
-[ ] clone the repository into the `staging` directory
-[ ] in the `zip` function pass a list of all repo root files and directory paths excluding the `.git` directory to the libgin `MakeZip` function
-[ ] remove usage of the `derepoCloneDir` function

**Comment by mpsonntag** [comment]
The suspicion that `git submodules` were to blame for the application freeze on the `git annex uninit` step could not be verified. Tests on a deployed DOI test server showed, that registration requests by repositories containing git submodules did not freeze the registration process and were completed without any issues.

**Comment by mpsonntag** [comment]
A repository that was known to cause the application freeze ([aswendtm/WT_Thrombin_4wks_T2w_DTI](https://gin.g-node.org/aswendtm/WT_Thrombin_4wks_T2w_DTI)) was used in further tests to narrow down the issue:
- a `git annex uninit` on a local clone of the mentioned repository did not cause any issues, the process finished within a short period of time.
- a clone of this repository to a deployed GIN test server instance and a DOI request to a connected DOI test server instance was initiated, the application froze again on the `git annex uninit` step.
- after removing the `git annex uninit` code from the DOI server codebase (function `derepoCloneDir`) and deploying this again as a DOI test server instance, a further registration request with the offending repository finished without any further issues.

**Comment by mpsonntag** [comment]
Closed via changes in PR #86.
